# Workflow temporarily disabled to avoid failed runs during Flask + Lightsail deployment
# name: Deploy to S3 + Invalidate CloudFront
# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v2
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: us-east-1

#       - name: Sync website to S3
#         run: aws s3 sync . s3://elitewebservices.net --delete --exact-timestamps

#       - name: Invalidate CloudFront cache
#         run: |
#           aws cloudfront create-invalidation \
#             --distribution-id E2QY2EQ08JUNT \
#             --paths "/*"
